services:
  webapi:
    image: webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    environment:
      ASPNETCORE_URLS: "http://+:5000"
      ASPNETCORE_HTTP_PORTS: 5000
    ports:
      - "8088:5000"
